wspr-ncsu/visiblev8

patches/faf34a95a93ff46eb360/trace-apis.diff, patches/faf34a95a93ff46eb360/version.txt
Applied on vanilla Chromium 83 and passed all tests beautifully.
=> Patches for Chrome 83.0.4103.116

patches/7c3f8264460ced0a6028/trace-apis-object.diff, patches/7c3f8264460ced0a6028/version.txt
- Changed argv indexing to start from 0 and not from 1 in visv8_log_api_call
- Moved call to visv8_log_api_call from HandleApiCallHelper(....) to HandleApiCall(...) since this allows us to cleanly get the function target
=> Fix function name and argument display issues

patches/7c3f8264460ced0a6028/trace-apis-object.diff, patches/8e1a5127113793e25c81/trace-apis-object.diff, tests/logs/relabel.py, tests/logs/trace-apis-obj/obj_func.log, tests/src/obj_func.js
=> Restrict iteration of object to only developer defined objs

post-processor/.gitignore, post-processor/Makefile, post-processor/README.md, post-processor/agg_entity_hashmap.py, post-processor/build_entity_hashmap.sh, post-processor/core/core.go, post-processor/fptp/load_emap.go, post-processor/fptp/main.go, post-processor/main.go
- Add first-party/third-party postprocessor
- Add documentation on how to use `adblock` and `fptp` postprocessor
- Update building instructions
=> Add first-party/third-party tracking postprocessor

builder/Makefile, builder/build-direct.sh, builder/check_new_chrome_release.sh, builder/github_release.sh, builder/run.sh, patches/22415abdab4ae42a6680/chrome-sandbox.diff, patches/22415abdab4ae42a6680/trace-apis.diff, patches/22415abdab4ae42a6680/version.txt
- Update Chrome 113 changes with android changes
- Provide Chrome sandbox changes diff file
- Update build system to support android builds
- Build android APK by default
=> Add Android changes

builder/build-direct.sh, patches/22415abdab4ae42a6680/trace-apis.diff, patches/22415abdab4ae42a6680/version.txt
- Fixed conflict with https://chromiumdash.appspot.com/commit/3804733594a321befda2e652236217d98031bfcd (Change in how is_contructor is determined in HandleApiCall)
- Fixed conflict with https://chromiumdash.appspot.com/commit/c30d2527d8b8403d13f2c36feeda3bef57db7acb (Addition of a new BUILD.gn variable for ios)
- Rename v8/tests/unittests to v8_unittests per https://chromiumdash.appspot.com/commit/4f7ed9200f10b9810930977c4a9cd35f719f31ae
=> Added support for Chrome 113

post-processor/callargs/callargs.go, post-processor/core/core.go, post-processor/features/features.go, post-processor/flow/main.go, post-processor/fptp/main.go, post-processor/mega/main.go, post-processor/micro/ufeatures.go
- The database entry says is-third-party but we were check if first-party, flipped it.
- Code cleanup, move some widely used functions to core module
=> Fix fptp postprocessor flipping third-party logic

patches/bb5258320e0aca193f0f/chrome-sandbox.diff, patches/bb5258320e0aca193f0f/trace-apis.diff, patches/bb5258320e0aca193f0f/version.txt
- Fix conflict with https://chromiumdash.appspot.com/commit/b5286d711f01a554bf0a519283a958dc602225e6 refactoring patch in js-call-reducer.cc
- Fix conflict with https://chromiumdash.appspot.com/commit/244cbf67c573ad21bb9bc1fb1202fb501224c58e refactoring patch in js-call-reducer.cc
=> Add patches for 114

builder/Makefile, builder/build-direct.sh, builder/check_new_chrome_release.sh, builder/install.sh, builder/run.sh, builder/vv82dockerhub.dockerfile, builder/vv82dockerhub.sh
=> Add support for building ARM versions of VisibleV8

.github/workflows/chromium-build.yaml
- Also make sure to trigger the build only if there are changes to specific directories
=> Add a cleanup step to the chromium build

.github/workflows/chromium-build.yaml, post-processor/fptp/main.go
=> Fix origin struct incompatibility with fptp

post-processor/adblock/main.go
=> Fix Rust panic due to origin struct difference

post-processor/flow/main.go
=> Fix issues with flow postprocessor wrt to Origin struct

patches/bb5258320e0aca193f0f/trace-apis.diff
=> Prevent sideeffects when querying properties of elements

builder/.dockerignore
=> Do not include .git_cache in docker builds

patches/6b4b19e9dfbb93aa414d/chrome-sandbox.diff, patches/6b4b19e9dfbb93aa414d/trace-apis.diff, patches/6b4b19e9dfbb93aa414d/version.txt
* Fixes for incompatibility with refactoring at https://chromium-review.googlesource.com/c/v8/v8/+/5205671
=> Add patches for Chrome 123

builder/build-direct.sh
=> Disable fieldtrials for visiblev8 builds

patches/cd0e5b0bca78ffe85d56/chrome-sandbox.diff, patches/cd0e5b0bca78ffe85d56/trace-apis.diff, patches/cd0e5b0bca78ffe85d56/version.txt
- Fixed rebase for js-call-reducer.cc https://chromiumdash.appspot.com/commit/76a5cea8606647b767792174876bc3bb501b1526 (refactoring patch)
=> Add patches for Chrome 124

post-processor/causality/causality.go, post-processor/tests/tests-artifacts/get-logs.sh, post-processor/tests/tests-artifacts/vv8-test/causality.html, post-processor/tests/tests-artifacts/vv8-test/i.html, post-processor/tests/tests-artifacts/vv8-test/manual-redir.html
- Add detection of javscript-side redirects to causality postprocessor
=> Add more changes to causality

patches/dce3cf294844dc54ae55/chrome-sandbox.diff, patches/dce3cf294844dc54ae55/trace-apis.diff, patches/dce3cf294844dc54ae55/version.txt
- https://chromiumdash.appspot.com/commit/e7c147b65c4f5c1013a0b45cf25fa291d176d111 Refactoring fixes related to handling execeptions in ApiFunctions
=> Add support for Chrome 126

patches/606aa55c7d687518d34b/chrome-sandbox.diff, patches/606aa55c7d687518d34b/trace-apis.diff, patches/606aa55c7d687518d34b/version.txt
-  Conflicts due to refactoring from https://chromium-review.googlesource.com/c/v8/v8/+/5614630
=> Add patches for Chrome 128

patches/3932fe54c45f96e7a1ab/chrome-sandbox.diff, patches/3932fe54c45f96e7a1ab/trace-apis.diff, patches/3932fe54c45f96e7a1ab/version.txt
- https://chromium-review.googlesource.com/c/chromium/src/+/5828084
(fix to some unrelated issue in dependency install script)
=> Support for Chrome 129

post-processor/fptp/main.go
- Example: "https://fundingchoicesmessages.google.com/f/AGSKWxUwttKXH2KyUA1Z7K2yaE17wePhXRkoL_jlnLT4J64n0BsPdPfu52BnLyVQbTxs_y30y3jinTmVqq-bMpBizU55lmE-gX0wsyeP0Y0P7_S8YIX1B3QkIgWjSyIsCiVTMEtLGWWkBVth30SPVpjGrBCKpA-8axPFk-N4DjxWts6lDc80WiWmD-Kx-8E7/_50%;)/get_banner.asp?/rightnavads./tag-adv./misc/ex_loader."
=> Fix fptp to handle invalid(ish) URLs

patches/613ff012cdbb0b7365da/chrome-sandbox.diff, patches/613ff012cdbb0b7365da/trace-apis.diff, patches/613ff012cdbb0b7365da/version.txt
- https://chromium-review.googlesource.com/c/v8/v8/+/5978304 (Object got partially replaced with JSAny)
- https://chromium-review.googlesource.com/c/v8/v8/+/5907404 (Reorganization wrt to V8Sandbox)
=> Support for Chrome 132

patches/2c6eb8e0ad4fc118077d/chrome-sandbox.diff, patches/2c6eb8e0ad4fc118077d/trace-apis.diff, patches/2c6eb8e0ad4fc118077d/version.txt
- https://chromium-review.googlesource.com/c/v8/v8/+/6074945 (Replaces DirectHandle with Handle, resulting in a few class conversions in our codebase)
=> Add support for Chrome 133

patches/ea6ef4c2ac15ae95d2cf/chrome-sandbox.diff, patches/ea6ef4c2ac15ae95d2cf/trace-apis.diff, patches/ea6ef4c2ac15ae95d2cf/version.txt
Refactoring collisions with ongoing work moving to DirectHandle vs Handle work in V8.
=> Add support for Chrome 134

patches/1f603f02d223378b95a0/chrome-sandbox.diff, patches/1f603f02d223378b95a0/trace-apis.diff, patches/1f603f02d223378b95a0/version.txt
(Should be) Rebases against refactoring fixes
=> Add support for Chrome 137
